#### GitHub Actions to check whether package can be built as is

name: Code Coverage

on:
  pull_request:
    branches: [dev]
    types: [closed]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      condition: ${{ steps.condition.outputs.condition }}
    steps:
      - id: condition
        run: |
          if [[ ${{ github.head_ref }} == *"main"* ]]; then
             echo "condition=false" >> $GITHUB_OUTPUT
          else
             echo "condition=true" >> $GITHUB_OUTPUT
          fi
  Badges:
    if: ${{ (github.event.pull_request.merged) && (needs.setup.outputs.condition) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MEP_Package_Update }}
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::badgen, any::dplyr, any::here, any::stringr
          needs: check

      - name: Calculate Code Coverage
        run: |
          source(".github/code_coverage.R")
        shell: Rscript {0}

      - name: Edit README.md file
        run: |
          source(".github/readme_edit.R")
        shell: Rscript {0}

      - name: Verify changes in the maelstrom_taxonomies sub-directory
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf # v20
        id: verify-changed-files
        with:
          files: |
            README.md
            status/badges

      - name: Commit files
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -am "chore: updating test coverage"
          git push

