#### GitHub Action to increment the public-facing version based on semantic versioning v2


name: Release
on:
  repository_dispatch:
    types: [semantic_release]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.MEP_Package_Update }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Install more dependencies
        run: npm install @semantic-release/git @semantic-release/changelog -D
      - name: Install more dependencies
        run: npm install @semantic-release/exec -D

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.MEP_Package_Update }}
        run: npx semantic-release

